- name: Normalize settings.gradle / settings.gradle.kts
  shell: bash
  run: |
    set -e
    ROOT="$PROJECT_DIR"

    write_settings_kts() {
      printf '%s\n' \
'pluginManagement {' \
'    repositories {' \
'        gradlePluginPortal()' \
'        google()' \
'        mavenCentral()' \
'    }' \
'}' \
'dependencyResolutionManagement {' \
'    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)' \
'    repositories {' \
'        google()' \
'        mavenCentral()' \
'    }' \
'}' \
'rootProject.name = "TitanApp"' \
'include(":app")' \
> "$ROOT/settings.gradle.kts"
    }

    write_settings_groovy() {
      printf '%s\n' \
'pluginManagement {' \
'    repositories {' \
'        gradlePluginPortal()' \
'        google()' \
'        mavenCentral()' \
'    }' \
'}' \
'dependencyResolutionManagement {' \
'    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)' \
'    repositories {' \
'        google()' \
'        mavenCentral()' \
'    }' \
'}' \
'rootProject.name = "TitanApp"' \
'include(":app")' \
> "$ROOT/settings.gradle"
    }

    if [ -f "$ROOT/settings.gradle.kts" ]; then
      cp "$ROOT/settings.gradle.kts" "$ROOT/settings.gradle.kts.bak" || true
      write_settings_kts
    else
      [ -f "$ROOT/settings.gradle" ] && cp "$ROOT/settings.gradle" "$ROOT/settings.gradle.bak" || true
      write_settings_groovy
    fi

    echo "Normalized settings file:"
    cat "$ROOT"/settings.gradle*
