
name: Build Titan (Debug APK)

on:
  workflow_dispatch:
  push:
    paths:
      - "TitanApp_Rebuild.zip"
      - ".github/workflows/android-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17", cache: gradle }
      - uses: android-actions/setup-android@v3
      - name: Unzip project
        run: unzip -q TitanApp_Rebuild.zip -d TitanApp
      - name: Install SDK components
        run: sdkmanager "platforms;android-34" "build-tools;34.0.0"
      - name: Build Debug APK
        working-directory: TitanApp
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: titan-debug-apk
          path: TitanApp/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14
