name: Build Android (auto-detect)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: sdkmanager "platforms;android-34" "build-tools;34.0.0"

      # ---------- Detect project root and app module ----------
      - name: Detect Android project + app module
        id: detect
        shell: bash
        run: |
          set -euo pipefail

          # 1) Detect project root (directory that has settings.gradle or settings.gradle.kts)
          ROOT="$(dirname "$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?)$' | head -n1 || true)")"
          if [ -z "${ROOT:-}" ] || [ "${ROOT}" = "." ]; then
            # Fallback: directory that has gradle.properties
            ROOT="$(git ls-files | grep -E '(^|/)(gradle\.properties)$' | sed 's#/gradle\.properties##' | head -n1 || true)"
          fi
          if [ -z "${ROOT:-}" ]; then ROOT="."; fi

          # 2) Detect app module (build.gradle* that applies com.android.application)
          APP_MOD="$(grep -RIl --include=build.gradle --include=build.gradle.kts -e 'com\.android\.application' "$ROOT" | head -n1 || true)"
          if [ -n "${APP_MOD:-}" ]; then
            APP_MOD="${APP_MOD#$ROOT/}"               # strip ROOT prefix
            APP_MOD="${APP_MOD%/build.gradle}"        # strip filename (Groovy)
            APP_MOD="${APP_MOD%/build.gradle.kts}"    # strip filename (Kotlin)
          fi
          if [ -z "${APP_MOD:-}" ] && [ -d "$ROOT/app" ]; then
            APP_MOD="app"
          fi
          if [ -z "${APP_MOD:-}" ]; then
            echo "::error::Could not determine application module (com.android.application)."
            echo "Looked under: $ROOT"
            exit 2
          fi

          echo "project_dir=${ROOT}"      >> "$GITHUB_OUTPUT"
          echo "app_module=${APP_MOD}"    >> "$GITHUB_OUTPUT"
          echo "Detected project_dir=$ROOT ; app_module=$APP_MOD"
