android {
  namespace 'com.example.titan'
  compileSdk 34

  defaultConfig {
    applicationId "com.example.titan"
    minSdk 26
    targetSdk 34
    versionCode 1
    versionName "1.0"
  }

  buildFeatures { compose true }
  composeOptions { kotlinCompilerExtensionVersion '1.5.14' }

  // ✅ Add this:
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

kotlin {
  // ✅ Add this toolchain block (top-level in the file, not inside android{})
  jvmToolchain(17)
}

// Keep this too:
kotlinOptions { jvmTarget = '17' }
