name: Build Titan (Debug APK)

on:
  workflow_dispatch:
  push:
    paths:
      - 'TitanApp_Rebuild.zip'
      - '.github/workflows/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -q TitanApp_Rebuild.zip -d TitanApp

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Download Gradle 8.7
        run: |
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH

      # 👉 Inject Java 17 + Kotlin toolchain into the unzipped project
      - name: Patch Gradle for Java 17
        run: |
          FILE="TitanApp/app/build.gradle"
          if [ -f "$FILE" ]; then
            # add compileOptions if missing
            if ! grep -q "compileOptions" "$FILE"; then
              awk '1; /composeOptions/ && !x {print "  compileOptions {\\n    sourceCompatibility JavaVersion.VERSION_17\\n    targetCompatibility JavaVersion.VERSION_17\\n  }"; x=1}' "$FILE" > tmp && mv tmp "$FILE"
            fi
            # add kotlin toolchain if missing
            if ! grep -q "jvmToolchain(17)" "$FILE"; then
              printf "\n// Injected by CI\nkotlin {\n  jvmToolchain(17)\n}\n" >> "$FILE"
            fi
          fi
          # tidy manifest package attribute (optional)
          MAN="TitanApp/app/src/main/AndroidManifest.xml"
          if [ -f "$MAN" ]; then
            sed -i 's/^\s*<manifest\s\+xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android"\s\+package="[^"]*">/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android">/' "$MAN" || true
          fi

      - name: Build Debug APK
        run: |
          gradle -v
          gradle -p TitanApp assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: titan-debug-apk
          path: TitanApp/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14
